/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as AuthenticatedRifasParticipadasRouteImport } from './routes/_authenticated/rifas-participadas'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedMinhasRifasRouteImport } from './routes/_authenticated/minhas-rifas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCriarRifaRouteImport } from './routes/_authenticated/criar-rifa'
import { Route as AuthenticatedRifasIdAprovacoesRouteImport } from './routes/_authenticated/rifas.$id.aprovacoes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRifasParticipadasRoute =
  AuthenticatedRifasParticipadasRouteImport.update({
    id: '/rifas-participadas',
    path: '/rifas-participadas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhasRifasRoute =
  AuthenticatedMinhasRifasRouteImport.update({
    id: '/minhas-rifas',
    path: '/minhas-rifas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriarRifaRoute = AuthenticatedCriarRifaRouteImport.update({
  id: '/criar-rifa',
  path: '/criar-rifa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRifasIdAprovacoesRoute =
  AuthenticatedRifasIdAprovacoesRouteImport.update({
    id: '/rifas/$id/aprovacoes',
    path: '/rifas/$id/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/criar-rifa': typeof AuthenticatedCriarRifaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minhas-rifas': typeof AuthenticatedMinhasRifasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/rifas-participadas': typeof AuthenticatedRifasParticipadasRoute
  '/r/$slug': typeof RSlugRoute
  '/rifas/$id/aprovacoes': typeof AuthenticatedRifasIdAprovacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/criar-rifa': typeof AuthenticatedCriarRifaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/minhas-rifas': typeof AuthenticatedMinhasRifasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/rifas-participadas': typeof AuthenticatedRifasParticipadasRoute
  '/r/$slug': typeof RSlugRoute
  '/rifas/$id/aprovacoes': typeof AuthenticatedRifasIdAprovacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/criar-rifa': typeof AuthenticatedCriarRifaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/minhas-rifas': typeof AuthenticatedMinhasRifasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/rifas-participadas': typeof AuthenticatedRifasParticipadasRoute
  '/r/$slug': typeof RSlugRoute
  '/_authenticated/rifas/$id/aprovacoes': typeof AuthenticatedRifasIdAprovacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/criar-rifa'
    | '/dashboard'
    | '/minhas-rifas'
    | '/perfil'
    | '/rifas-participadas'
    | '/r/$slug'
    | '/rifas/$id/aprovacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/criar-rifa'
    | '/dashboard'
    | '/minhas-rifas'
    | '/perfil'
    | '/rifas-participadas'
    | '/r/$slug'
    | '/rifas/$id/aprovacoes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/criar-rifa'
    | '/_authenticated/dashboard'
    | '/_authenticated/minhas-rifas'
    | '/_authenticated/perfil'
    | '/_authenticated/rifas-participadas'
    | '/r/$slug'
    | '/_authenticated/rifas/$id/aprovacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RSlugRoute: typeof RSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/rifas-participadas': {
      id: '/_authenticated/rifas-participadas'
      path: '/rifas-participadas'
      fullPath: '/rifas-participadas'
      preLoaderRoute: typeof AuthenticatedRifasParticipadasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minhas-rifas': {
      id: '/_authenticated/minhas-rifas'
      path: '/minhas-rifas'
      fullPath: '/minhas-rifas'
      preLoaderRoute: typeof AuthenticatedMinhasRifasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar-rifa': {
      id: '/_authenticated/criar-rifa'
      path: '/criar-rifa'
      fullPath: '/criar-rifa'
      preLoaderRoute: typeof AuthenticatedCriarRifaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rifas/$id/aprovacoes': {
      id: '/_authenticated/rifas/$id/aprovacoes'
      path: '/rifas/$id/aprovacoes'
      fullPath: '/rifas/$id/aprovacoes'
      preLoaderRoute: typeof AuthenticatedRifasIdAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCriarRifaRoute: typeof AuthenticatedCriarRifaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMinhasRifasRoute: typeof AuthenticatedMinhasRifasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRifasParticipadasRoute: typeof AuthenticatedRifasParticipadasRoute
  AuthenticatedRifasIdAprovacoesRoute: typeof AuthenticatedRifasIdAprovacoesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCriarRifaRoute: AuthenticatedCriarRifaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMinhasRifasRoute: AuthenticatedMinhasRifasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRifasParticipadasRoute: AuthenticatedRifasParticipadasRoute,
  AuthenticatedRifasIdAprovacoesRoute: AuthenticatedRifasIdAprovacoesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RSlugRoute: RSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
